### ISSUE TITLE
Incorrectly hiding the navigation menu

### ISSUE THREAD

**Issue by petira** [tranduyhung/grav-theme-multiverse#8]
Hi!

First of all I have to praise a nice theme for a simple gallery.

If the gallery page is scrolled up, the navigation menu correctly hides behind the bottom edge when the zoom mode is activated. I think this applies until the bottom border is equal to the height of the navigation menu. Then the menu moves illogically up to the gallery. Although it is in the background and blurred, it still gives a disturbing impression.

If the page is in mobile mode, then the same applies, but in reverse.

Can you please look at the CSS and adjust the values so that the navigation menu is hidden behind the bottom or top edge always?

**Comment by tranduyhung** [comment]
I don't see the problems you described and I see that the theme is working the same to the original upstream HTML template https://html5up.net/multiverse. We made no changes to the code, CSS and JS are the same to the HTML template.

**Comment by petira** [comment]
You are right, the behavior is the same in the original. So consider it irrelevant, I will try to modify the CSS for my needs and send it to you if necessary.
